project:
  type: website

website:
  title: "RissoLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research Interests & Output
      - href: people.qmd
        text: People
      - href: projects.qmd
        text: Current Funded Projects
      - href: jobs.qmd
        text: Work with us
      - href: news.qmd
        text: News & Events


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
editor: visual

